'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '../components/Sidebar'
import Rightside from '../components/Rightside'
import { RecoilRoot } from 'recoil'
import { NextAuthProvider } from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <RecoilRoot>
        <body className="body container mx-auto">
          <NextAuthProvider>
          
          <Sidebar />
          {children}
          <Rightside />
          </NextAuthProvider>
        </body>
      </RecoilRoot>
    </html>
  )
}
